export const PHONENUMBER = 'PHONENUMBER'
export const OTP = 'OTP'
export const PASSWORD = 'PASSWORD'
export const CONFIRMPASSWORD = 'CONFIRMPASSWORD'
export const MOBILEERROR = 'MOBILEERROR'
export const OTPERROR = 'OTPERROR'
